# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GCDTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GCDTest
  pod 'AFNetworking', '~> 3.1.0'
   pod 'MJRefresh', '~> 3.1.15.1'

  target 'GCDTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GCDTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
